# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

topic_ar <- function(X, sigma, L, n_p, iter, lr, actfun) {
    .Call(`_topicar_topic_ar`, X, sigma, L, n_p, iter, lr, actfun)
}

